package vn.viettuts.qlsv.view;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import vn.viettuts.qlsv.dao.OrderDetailDao;
import vn.viettuts.qlsv.dao.ProductDao;
import vn.viettuts.qlsv.entity.OrderDetail;
import vn.viettuts.qlsv.entity.Product;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class Chart extends javax.swing.JFrame {

    private ChartPanel chartPanelProductQuantity;
    private ChartPanel chartPanelProductExport;

    /**
     * Creates new form Chart
     */
    public Chart() {
        initComponents();
        setLocationRelativeTo(null);

    }

    private void createProductQuantityChartPanel() {
        DefaultCategoryDataset dataset = createProductQuantityDataset();

        JFreeChart chart = ChartFactory.createBarChart(
                "Biểu đồ số lượng sản phẩm",
                "Tên sản phẩm",
                "Số lượng",
                dataset,
                org.jfree.chart.plot.PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        CategoryPlot plot = chart.getCategoryPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, Color.GREEN);
        // Tạo một panel cho biểu đồ
        chartPanelProductQuantity = new ChartPanel(chart);
        chartPanelProductQuantity.setPreferredSize(new java.awt.Dimension(680, 400));
    }

    private DefaultCategoryDataset createProductQuantityDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        ProductDao productDao = new ProductDao();
        List<Product> products = productDao.getProducts();

        for (Product product : products) {
            dataset.addValue(Integer.parseInt(product.getQuantity()), "Số lượng", product.getProductName());
        }

        return dataset;
    }

    private void createProductExportChartPanel() {
        DefaultCategoryDataset dataset = createProductExportDataset();

        JFreeChart chart = ChartFactory.createBarChart(
                "Biểu đồ sản phẩm xuất",
                "Tên sản phẩm",
                "Số lượng xuất",
                dataset,
                org.jfree.chart.plot.PlotOrientation.VERTICAL,
                true,
                true,
                false
        );

        chartPanelProductExport = new ChartPanel(chart);
        chartPanelProductExport.setPreferredSize(new java.awt.Dimension(680, 400));
    }

    private DefaultCategoryDataset createProductExportDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        OrderDetailDao orderDetailDao = new OrderDetailDao();
        List<OrderDetail> orderDetails = orderDetailDao.getOrderDetailList();

        // Thêm dữ liệu vào dataset
        for (OrderDetail orderDetail : orderDetails) {
            dataset.addValue(Integer.parseInt(orderDetail.getProductQuantity()), "Số lượng xuất", orderDetail.getProductName());
        }

        return dataset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createProductQuantityChartPanel();
        createProductExportChartPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chartPanelProductQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chartPanelProductExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(chartPanelProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chartPanelProductExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
