/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.viettuts.qlsv.view;

import java.awt.event.ActionListener;

/**
 * @author Administrator
 */
public class MainMenuView extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuView
     */
    public MainMenuView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProduct = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExporter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnStatics = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProduct.setText("Nhập sản phẩm");
        getContentPane().add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 65, -1, 47));

        btnLogout.setText("Đăng xuất");
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 114, 47));

        btnExporter.setText("Xuất sản phẩm");
        getContentPane().add(btnExporter, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 65, -1, 47));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chọn chức năng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 15, -1, -1));

        btnStatics.setText("Báo cáo");
        getContentPane().add(btnStatics, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 114, 47));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z5536159931127_87ac2b07fee70f1c2fb43b06c741d660.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setBtnProduct(ActionListener actionListener) {
        btnProduct.addActionListener(actionListener);
    }

    public void setBtnExporter(ActionListener actionListener) {
        btnExporter.addActionListener(actionListener);
    }

    public void setBtnLogout(ActionListener actionListener) {
        btnLogout.addActionListener(actionListener);
    }
    public void setBtnStatics(ActionListener actionListener) {
        btnStatics.addActionListener(actionListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExporter;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnStatics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
