/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.viettuts.qlsv.view;

import vn.viettuts.qlsv.entity.OrderDetail;
import vn.viettuts.qlsv.entity.Product;

import java.util.List;
import java.util.Objects;

/**
 * @author Administrator
 */
public class OrderDetailView extends javax.swing.JFrame {

    /**
     * Creates new form OrderDetailView
     */
    public OrderDetailView() {
        initComponents();

        txtOrderId.setEditable(false);
        txtProductName.setEditable(false);
        txtProductPrice.setEditable(false);

        txtId.setEditable(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtOrderId = new javax.swing.JTextField();
        cbProductId = new javax.swing.JComboBox<>();
        txtProductName = new javax.swing.JTextField();
        txtProductPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrderDetails = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtRemaning = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chi tiết phiếu hàng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("STT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 87, 37, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã phiếu xuất:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 127, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã sản phẩm:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 167, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên sản phẩm:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 207, 105, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giá sản phẩm:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 247, 105, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số lượng xuất:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 287, 105, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 87, 163, -1));
        getContentPane().add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 127, 163, -1));

        cbProductId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 167, 163, -1));
        getContentPane().add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 207, 163, -1));
        getContentPane().add(txtProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 247, 163, -1));
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 287, 163, -1));

        tbOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Mã đơn hàng", "Mã sản phẩm", "Tên sản phẩm", "Giá/sản phẩm", "Số lượng xuất"
            }
        ));
        tbOrderDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbOrderDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbOrderDetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 600, 430));

        btnAdd.setText("Thêm");
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 376, 76, -1));

        btnDelete.setText("Xoá");
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 376, 78, -1));

        btnRefresh.setText("Làm mới");
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 417, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số lượng còn lại:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 327, -1, -1));
        getContentPane().add(txtRemaning, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 327, 163, -1));

        btnUpdate.setText("Cập nhật");
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 417, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z5536159931127_87ac2b07fee70f1c2fb43b06c741d660.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbOrderDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbOrderDetailsMouseClicked
        int selectedRow = tbOrderDetails.getSelectedRow();
        txtId.setText(tbOrderDetails.getValueAt(selectedRow, 0).toString());
        txtOrderId.setText(tbOrderDetails.getValueAt(selectedRow, 1).toString());
        cbProductId.setSelectedItem(tbOrderDetails.getValueAt(selectedRow, 2).toString());
        txtProductName.setText(tbOrderDetails.getValueAt(selectedRow, 3).toString());
        txtProductPrice.setText(tbOrderDetails.getValueAt(selectedRow, 4).toString());
        txtQuantity.setText(tbOrderDetails.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_tbOrderDetailsMouseClicked

    public OrderDetail getOrderDetailInput() {
        String id = txtId.getText();
        String orderId = txtOrderId.getText();
        String productId = Objects.requireNonNull(cbProductId.getSelectedItem()).toString();
        String productName = txtProductName.getText();
        String productPrice = txtProductPrice.getText();
        String quantity = txtQuantity.getText();

        if (id.isEmpty() || orderId.isEmpty() || productId.isEmpty() || productName.isEmpty() || productPrice.isEmpty() || quantity.isEmpty()) {
            throw new IllegalArgumentException("Vui lòng nhập đầy đủ thông tin");
        }

        try {
            Integer.parseInt(quantity);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Giá sản phẩm và số lượng xuất phải là số");
        }
        return new OrderDetail(id, orderId, productId, productName, productPrice, quantity);

    }


    public void setBtnAddActionListener(java.awt.event.ActionListener actionListener) {
        btnAdd.addActionListener(actionListener);
    }

    public void setBtnDeleteActionListener(java.awt.event.ActionListener actionListener) {
        btnDelete.addActionListener(actionListener);
    }

    public void setBtnRefreshActionListener(java.awt.event.ActionListener actionListener) {
        btnRefresh.addActionListener(actionListener);
    }

    public void setCbProductIdActionListener(java.awt.event.ActionListener actionListener) {
        cbProductId.addActionListener(actionListener);
    }

    public void setBtnUpdateActionListener(java.awt.event.ActionListener actionListener) {
        btnUpdate.addActionListener(actionListener);
    }

    public void setCbProductId(List<String> productIdList) {
        cbProductId.removeAllItems();
        for (String productId : productIdList) {
            cbProductId.addItem(productId);
        }

        cbProductId.setSelectedIndex(-1);

    }

    public void setTxtOrderId(String orderId) {
        txtOrderId.setText(orderId);
    }



    public void setDataToTable(List<OrderDetail> orderDetailList) {
        tbOrderDetails.removeAll();

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("STT");
        model.addColumn("Mã đơn hàng");
        model.addColumn("Mã sản phẩm");
        model.addColumn("Tên sản phẩm");
        model.addColumn("Giá sản phẩm");
        model.addColumn("Số lượng xuất");

        for (OrderDetail orderDetail : orderDetailList) {
            model.addRow(new Object[]{orderDetail.getId(), orderDetail.getOrderId(), orderDetail.getProductId(), orderDetail.getProductName(), orderDetail.getProductPrice(), orderDetail.getProductQuantity()});
        }
        tbOrderDetails.setModel(model);
    }

    public void setTxtId(int id) {
        txtId.setText(String.valueOf(id + 1));
    }

    public void clear(int id) {
        txtId.setText(String.valueOf(id + 1));
        txtProductName.setText("");
        txtProductPrice.setText("");
        txtQuantity.setText("");
        txtRemaning.setText("");
        tbOrderDetails.clearSelection();
        cbProductId.setSelectedItem(-1);
    }
    public String getCbProductId() {
        return Objects.requireNonNull(cbProductId.getSelectedItem()).toString();
    }

    public void setProductDetail(Product p){
        txtProductName.setText(p.getProductName());
        txtProductPrice.setText(p.getPrice());
        txtRemaning.setText(p.getQuantity());
    }

    public String getRemaining(){
        return txtRemaning.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbProductId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbOrderDetails;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRemaning;
    // End of variables declaration//GEN-END:variables
}
